-- ==========================================
-- MatchUp AI Database Schema & Initial Data
-- Run this in your Supabase SQL Editor
-- ==========================================

-- 1. PROFILES TABLE
CREATE TABLE IF NOT EXISTS public.profiles (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID,
    full_name TEXT NOT NULL DEFAULT 'Alex Sterling',
    email TEXT UNIQUE NOT NULL,
    phone_number TEXT,
    country_code TEXT DEFAULT '+62',
    gender TEXT,
    domicile TEXT DEFAULT 'San Francisco, CA',
    highest_degree TEXT DEFAULT 'Master of Human-Computer Interaction',
    field_of_study TEXT DEFAULT 'Human-Computer Interaction',
    institution TEXT DEFAULT 'Stanford University',
    interests JSONB DEFAULT '{"engineering": true, "design": true, "marketing": false, "management": false}'::jsonb,
    workplace TEXT DEFAULT 'Remote Only',
    avatar_url TEXT DEFAULT 'https://lh3.googleusercontent.com/aida-public/AB6AXuB76RUL1uTVLe5VyCjVzkutfx4CdLsSdHFLUV3-QfUV2eueL-USc-oeaK3hvQWDuL4iBzpGncrpthEzF_U_jttVwhw4BtA5kXHiTaDwJGg75uY1Ni9qC-9_S-LqseWAcQUuikWPh7MtrgH7eC8nEQWxMub3KYbthu_sCho__Bv7JOVEsvfpHxFu56SXiXo1poZoMN1vaHzQqoCbnjnZIIVidQkmkrhUqc3_GK84zvV1hcw-rCn8xziD',
    readiness_score INT DEFAULT 92,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. JOBS TABLE
CREATE TABLE IF NOT EXISTS public.jobs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    company TEXT NOT NULL,
    logo TEXT,
    match_score INT DEFAULT 85,
    salary TEXT NOT NULL,
    location TEXT NOT NULL,
    type TEXT DEFAULT 'Full-time',
    posted TEXT DEFAULT 'Recently',
    applicants INT DEFAULT 12,
    tags TEXT[] DEFAULT '{}',
    category TEXT DEFAULT 'All',
    description TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. SAVED JOBS TABLE
CREATE TABLE IF NOT EXISTS public.saved_jobs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_email TEXT NOT NULL,
    job_id BIGINT REFERENCES public.jobs(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(user_email, job_id)
);

-- 4. APPLIED JOBS TABLE
CREATE TABLE IF NOT EXISTS public.applied_jobs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_email TEXT NOT NULL,
    job_id BIGINT REFERENCES public.jobs(id) ON DELETE CASCADE,
    status TEXT DEFAULT 'Under Review',
    applied_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(user_email, job_id)
);

-- 5. USER CVS TABLE
CREATE TABLE IF NOT EXISTS public.user_cvs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_email TEXT NOT NULL,
    file_name TEXT NOT NULL,
    file_url TEXT,
    analysis_score INT DEFAULT 85,
    extracted_skills JSONB DEFAULT '[]'::jsonb,
    uploaded_at TIMESTAMPTZ DEFAULT NOW()
);

-- ENABLE ROW LEVEL SECURITY (RLS)
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.jobs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.saved_jobs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.applied_jobs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_cvs ENABLE ROW LEVEL SECURITY;

-- CREATE RLS POLICIES (Allow Public Anon Read/Write for easy demo access)
CREATE POLICY "Allow public read jobs" ON public.jobs FOR SELECT USING (true);
CREATE POLICY "Allow public insert jobs" ON public.jobs FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public update jobs" ON public.jobs FOR UPDATE USING (true);

CREATE POLICY "Allow public all profiles" ON public.profiles FOR ALL USING (true);
CREATE POLICY "Allow public all saved_jobs" ON public.saved_jobs FOR ALL USING (true);
CREATE POLICY "Allow public all applied_jobs" ON public.applied_jobs FOR ALL USING (true);
CREATE POLICY "Allow public all user_cvs" ON public.user_cvs FOR ALL USING (true);

-- INITIAL SEED DATA FOR JOBS
INSERT INTO public.jobs (id, title, company, logo, match_score, salary, location, type, posted, applicants, tags, category, description)
VALUES 
(1, 'Senior Product Designer', 'Nebula Cloud Systems', 'https://lh3.googleusercontent.com/aida-public/AB6AXuDxbBmFaRupELCRS8PACJLUn_ruWppU6Ql60sITI67F1xsr4vwYNyNjCYffWp1x6lcCNuT0rOvAa94SMlsndq_p8GZcyhcgCLhEpRh6WjF8RqwL3UkUIU832WU9MA-h-oO22kCG2_AMvtXwUW0Gug1pFKykjeB6WZMHpDlyWCCbVHQ9h5EhIcR4uzYy302ETAxik8JSOAGUF6atyjZX-Nr_5mi7aZoh2qnqyRE0Dk6afHEaH9dn8aYH', 98, '$160k - $210k', 'San Francisco, CA', 'Full-time', '2 days ago', 128, ARRAY['Figma', 'Design Systems', 'SaaS'], 'Remote Only', 'We are looking for a Senior Product Designer to lead design initiatives.'),
(2, 'Lead UX Architect', 'Vertex Solutions', 'https://lh3.googleusercontent.com/aida-public/AB6AXuCpZCvYkfm36cNGMvfjLGkkwGS_rV_qofDtiIGEjXLfjuBfsp_mDJVhcOxnOjpwTIuZ_4GzzejS7RAm_PRgCozFJVyKBURXkX1NRYi_YevVgvKIclrSur3nVL7JF69yLU5kqhL13xOiXhevRrbCyL3fBo10X9vO9vHYma85XUf0Eqg2m0zpkhmVci2WM53pEBILqKLoiZpO-jCd0h3yU3qOcGCkUGISgaELqarOYuoJLeajG41Z8thy', 94, '$145k - $185k', 'Remote', 'Remote Only', '1 day ago', 94, ARRAY['UX Architect', 'User Research', 'Figma'], 'Remote Only', 'Architect modern user experiences across platform touchpoints.'),
(3, 'Interaction Engineer', 'Flow AI', 'https://lh3.googleusercontent.com/aida-public/AB6AXuB9LxAFSmIhOX9YEh-ORzXmf1oEvvce8Sxx6vLMKNmmWA8HU0vrtzhmyvbX6-S-8n3t2UTr_cgCxYyCAn5gvXXSxwpIE7GFaMv-V93YRegAstfgbmTLWB7_iALLWk7zIxZm5eHVadnXpSG8uNw59r8yZbYNm4fSqxrAKb0tclmEc2S6NadmXhXgLAIq5sJwoGZP_a2uKoTcaZ6GSNn0AJQdsCxcqoMFZEKby6UJfIgheQNm78GlE-Uu', 91, '$130k - $175k', 'Austin, TX', 'Full-time', '3 days ago', 45, ARRAY['React', 'Framer Motion', 'Tailwind'], 'High Match Score', 'Design and build interactive motion UI systems for AI platforms.'),
(4, 'Product Strategist', 'Stellar Data', 'https://lh3.googleusercontent.com/aida-public/AB6AXuDGTWLTBBnBk5QIjq2QrHkqnqAYQZAuKyy8R8RC260iorcK66MjNUyZy17dt74hNktJLyZEJ1SoYLCJAsovjFvN0jW39ByCZdHca3Uq58dqzrGidJdHqaEuQ_bAABx77OOLZmciUEbUz_qhBJ0hK9bW4UoDXP95jj02Zrp-QZjzA-_zHQ4kVtXJgAg_0Hxj-oWOXuhs7RsfpefhiE9HTiwaZA1WvkTOcV1QsuUHVs-Ra2pc9ljlgov9', 89, '$155k - $190k', 'New York, NY', 'Full-time', '4 days ago', 67, ARRAY['Product Strategy', 'Analytics', 'Growth'], 'All', 'Drive high-impact product roadmap alignment with executive partners.'),
(5, 'UI Engineer', 'Helix Health', 'https://lh3.googleusercontent.com/aida-public/AB6AXuARXRO46cWWsfHg_Zi9BohKgJwAaCd1nmf2dLRKBXvwyAO-vXvGau-rtghZ4foxxG1w2PW9Ovo1Byh_62JujspoH23_E1jhKnNl52QZx2cIKh0mJ2W-vcR4RSptZOclNTQVD1UmqR_QReQ-m3o1q6SCYM1ABTvbBB42RalxSxjRSi2N5PBAFLME1N8NKvjTyggPJyLFFnchywBJdziOENFY7Zoxqm_KlZMSFJZ9Wb8YTanj8x_-1c27', 87, '$140k - $170k', 'Remote', 'Remote Only', '5 days ago', 52, ARRAY['React', 'Design Systems', 'CSS'], 'Remote Only', 'Build resilient web design systems for digital healthcare tools.'),
(6, 'System Architect', 'Quantum Labs', 'https://lh3.googleusercontent.com/aida-public/AB6AXuCTXOkK8qr46Ln7yYfj36UjAH9_1N1EmEXzaVAomnXLz6KrTFPDdo_3BACOuGMDkKjckL9YF8cMV4Bfesy6SsTxAknmwLBqnAX4OZAr4Qb2-ynmmUAklsayD_DPm6lHCBaUrYm2wnn_ScmGuHDstKJZLCYwsW1N9PBGZ3FvtccSvJC1k6A1QXk-O6jLVQUHqlNQMY1b0y-0Eq-YRLdNnzzj4E7O3ibUe6N9kbkEY57TKHsvzDgBPQe_', 85, '$175k - $225k', 'Palo Alto, CA', 'Full-time', '6 days ago', 89, ARRAY['Distributed Systems', 'Cloud', 'Architecture'], 'All', 'Architect scalable multi-cloud infrastructure for AI compute.')
ON CONFLICT (id) DO UPDATE 
SET title = EXCLUDED.title,
    company = EXCLUDED.company,
    logo = EXCLUDED.logo,
    match_score = EXCLUDED.match_score,
    salary = EXCLUDED.salary,
    location = EXCLUDED.location,
    type = EXCLUDED.type,
    posted = EXCLUDED.posted,
    applicants = EXCLUDED.applicants,
    tags = EXCLUDED.tags,
    category = EXCLUDED.category,
    description = EXCLUDED.description;

-- INITIAL SEED DATA FOR DEMO PROFILE
INSERT INTO public.profiles (id, full_name, email, domicile, highest_degree, readiness_score)
VALUES 
('a0000000-0000-0000-0000-000000000001', 'Alex Sterling', 'alex.sterling@example.com', 'San Francisco, CA', 'Master of Human-Computer Interaction', 92)
ON CONFLICT (email) DO NOTHING;
